const productRoutes = require("./product-route");
const homeRoutes = require("./home-route");
const searchRoutes = require("../../routes/client/search-route");
const cartRoutes = require("../../routes/client/cart-route");
const checkoutRoutes = require("../../routes/client/checkout-route");
const userRoutes = require("../../routes/client/user-route");
const chatRoutes = require("../../routes/client/chat-route");
const usersRoutes = require("../../routes/client/users-route");
const categoryMiddleware = require("../../middlewares/client/category-middleware");
const cartMiddleware = require("../../middlewares/client/cart-middleware");
const userMiddleware = require("../../middlewares/client/user.middleware");
const settingMiddleware = require("../../middlewares/client/setting.middleware");
const authMiddleware = require("../../middlewares/client/auth.middleware");
module.exports = (app) => {
  app.use(categoryMiddleware.category);
  app.use(cartMiddleware.cartID);
  app.use(userMiddleware.infoUser);
  app.use(settingMiddleware.settingGeneral);
  app.use("/", homeRoutes);
  app.use("/products", productRoutes);
  app.use("/search", searchRoutes);
  app.use("/cart", cartRoutes);
  app.use("/checkout", checkoutRoutes);
  app.use("/user", userRoutes);
  app.use("/chat", authMiddleware.requireAuth, chatRoutes);
  app.use("/users", authMiddleware.requireAuth, usersRoutes);
};
